export const TOKENS = {
  SOL: 'So11111111111111111111111111111111111111112',
  USDC: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
  USDT: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
};

export const TRANSLATIONS = {
  zh: {
      title: 'Solana 全自动刷量 (无弹窗版)',
      rpcLabel: 'RPC 节点 URL (公共节点必挂，请用 Helius/QuickNode)',
      privateKeyLabel: '私钥 (Base58) - 仅限小额 Burner 钱包!',
      apiKeyLabel: 'Jupiter API Key (可选)',
      apiKeyPlaceholder: '如果不填则使用公共限流模式',
      minAmountLabel: '最小金额',
      maxAmountLabel: '最大金额',
      countLabel: '循环次数',
      minIntervalLabel: '最小间隔 (ms)',
      maxIntervalLabel: '最大间隔 (ms)',
      slippageLabel: '滑点 (%)',
      priorityFeeLabel: '优先费 (SOL)',
      startBtn: '开始全自动交易',
      stopBtn: '停止运行',
      userStop: '🛑 用户请求停止...',
      scriptStop: '🛑 脚本已手动终止',
      scriptStart: '🤖 脚本启动 | 钱包:',
      buying: '🟢 买入',
      selling: '🔴 卖出',
      quantity: '数量',
      coolDown: '⏳ 冷却',
      tradeFail: '⚠️ 交易失败，3秒后自动重试...',
      reverseFailSkip: '⚠️ 反向交易失败，跳过并重置为正向交易...',
      fatalError: '❌ 致命错误:',
      taskEnd: '🏁 任务结束',
      txSuccess: '✅ 请求已发送! Tx:',
      txConfirmFail: '交易上链失败',
      txGet: '🎉 成交成功:',
      txGetSuffix: '(已获得代币)',
      txTimeout: '⚠️ 确认超时 (可能已成功):',
      rpcError403: 'RPC拒绝(403): 公共节点已封锁，请务必更换为 Helius/QuickNode 私有节点！',
      filterAll: '全部',
      filterSuccess: '已发送',
      filterGet: '只看成交',
      filterError: '只看失败',
      noLogs: '暂无日志',
      viewTx: '[查看交易]',
      privateKeyPlaceholder: '填入私钥...',
      privateKeyError: '必须输入私钥才能自动签名',
      privateKeyFormatError: '私钥格式错误 (请使用 Base58 格式)',
      publicRpcWarning: '警告：使用公共 RPC 极易失败，建议更换 Helius/QuickNode',
      amountHelp: '每次正向交易(如SOL->USDC)将在"最小金额"和"最大金额"之间随机取值，模拟真实用户行为；反向交易(如USDC->SOL)则会卖出上一步获得的全部代币，实现"乒乓"平衡。',
      countHelp: '总共执行的交易次数。一次买入算一次，一次卖出算一次。例如设置为5，则执行顺序为：买->卖->买->卖->买，最后持有代币。',
      intervalHelp: '两次交易之间的等待时间将在"最小间隔"和"最大间隔"之间随机取值，模拟真实用户行为。',
      slippageHelp: '允许的最大价格偏差。如果实际成交价超过此偏差，交易将被取消以保护您的资金。建议设置在 0.5% - 1.0% 之间。',
      priorityFeeHelp: '支付给矿工的额外费用，用于在网络拥堵时加快交易确认速度。单位为 SOL。',
      configRestorePrompt: '检测到上次使用的脚本配置（不包含私钥），是否一键恢复？',
      saveConfigBtn: '保存配置（不含私钥）',
      saveConfigSuccess: '配置已保存（不包含私钥）',
      saveConfigError: '配置保存失败，请检查浏览器存储权限',
      saveConfigHelp: '将当前参数（RPC、代币、金额、间隔、滑点等）保存到浏览器的 localStorage，方便下次一键恢复。不会保存私钥，需要每次手动输入。',
  },
  en: {
      title: 'Solana Auto Volume Bot (No Popup)',
      rpcLabel: 'RPC Node URL (Public nodes fail often, use Helius/QuickNode)',
      privateKeyLabel: 'Private Key (Base58) - Burner Wallet Only!',
      apiKeyLabel: 'Jupiter API Key (Optional)',
      apiKeyPlaceholder: 'Public rate limits apply if empty',
      minAmountLabel: 'Min Amount',
      maxAmountLabel: 'Max Amount',
      countLabel: 'Loop Count',
      minIntervalLabel: 'Min Interval (ms)',
      maxIntervalLabel: 'Max Interval (ms)',
      slippageLabel: 'Slippage (%)',
      priorityFeeLabel: 'Priority Fee (SOL)',
      startBtn: 'Start Auto-Trade',
      stopBtn: 'Stop Running',
      userStop: '🛑 User requested stop...',
      scriptStop: '🛑 Script manually terminated',
      scriptStart: '🤖 Script Started | Wallet:',
      buying: '🟢 Buy',
      selling: '🔴 Sell',
      quantity: 'Qty',
      coolDown: '⏳ Cooldown',
      tradeFail: '⚠️ Trade failed, retrying in 3s...',
      reverseFailSkip: '⚠️ Reverse trade failed, skipping to next Forward trade...',
      fatalError: '❌ Fatal Error:',
      taskEnd: '🏁 Task Ended',
      txSuccess: '✅ Sent! Tx:',
      txConfirmFail: 'Transaction failed to confirm',
      txGet: '🎉 Filled:',
      txGetSuffix: '(Tokens received)',
      txTimeout: '⚠️ Confirm timeout (might be success):',
      rpcError403: 'RPC Rejected (403): Public node blocked, MUST use Helius/QuickNode!',
      filterAll: 'All',
      filterSuccess: 'Sent',
      filterGet: 'Filled',
      filterError: 'Errors',
      noLogs: 'No logs yet',
      viewTx: '[View Tx]',
      privateKeyPlaceholder: 'Enter private key...',
      privateKeyError: 'Private key required for auto-signing',
      privateKeyFormatError: 'Invalid Private Key (Base58 required)',
      publicRpcWarning: 'Warning: Public RPCs fail often, recommend Helius/QuickNode',
      amountHelp: 'Forward trades (e.g. SOL->USDC) use a random value between "Min" and "Max" amounts. Reverse trades (e.g. USDC->SOL) sell ALL tokens from previous step for "Ping-Pong" balance.',
      countHelp: 'Total number of trades to execute. One buy counts as 1, one sell counts as 1. E.g. Set to 5: Buy->Sell->Buy->Sell->Buy, ending with tokens held.',
      intervalHelp: 'Wait time between trades uses a random value between "Min" and "Max" intervals.',
      slippageHelp: 'Maximum allowed price deviation. Trade will fail if price moves beyond this to protect your funds. 0.5% - 1.0% recommended.',
      priorityFeeHelp: 'Extra fee paid to validators to speed up confirmation during congestion. Unit: SOL.',
      configRestorePrompt: 'Detected a previous script configuration (excluding private key). Restore it now?',
      saveConfigBtn: 'Save config (no private key)',
      saveConfigSuccess: 'Config saved (private key not stored)',
      saveConfigError: 'Failed to save config. Please check browser storage settings',
      saveConfigHelp: 'Save current settings (RPC, tokens, amounts, intervals, slippage, etc.) into browser localStorage for quick restore next time. Private key is NOT stored; you must paste it manually each run.',
  }
};

export const DEFAULT_CONFIG = {
  RPC_URL: 'https://api.mainnet-beta.solana.com',
  AMOUNT: 0.01,
  TRADE_COUNT: 10,
  INTERVAL_MS: 3000,
  SLIPPAGE: 0.5,
  PRIORITY_FEE: 0.00001,
};